### ISSUE TITLE
invalid forward file for PE library 'pe': '/root/result/frag_1.fastq' Bad file descriptor

### ISSUE THREAD

**Issue by WJT0925** [aakashsur/docker-masurca#1]
Hi，I pull the masurca from docker, and first I do:
**docker run -it -v ~/Project/donghai/masurca:/root/result aakashsur/masurca /bin/bash**
then I do:
**masurca -i /root/result/frag_1.fastq,/root/result/frag_2.fastq -t 30**
and, this is the error:
**Error line 3 of configuration file 'config.txt':
invalid forward file for PE library 'pe': '/root/result/frag_1.fastq' Bad file descriptor
bash: ./assemble.sh: No such file or directory**

what's wrong with my command?

This is the config.txt:
**# quick run configuration file
DATA
PE = pe 500 50 /root/result/frag_1.fastq /root/result/frag_2.fastq
END
PARAMETERS
EXTEND_JUMP_READS=0
GRAPH_KMER_SIZE = auto
USE_LINKING_MATES = 1
USE_GRID=0
GRID_ENGINE=SGE
GRID_QUEUE=all.q
GRID_BATCH_SIZE=500000000
LHE_COVERAGE=25
LIMIT_JUMP_COVERAGE = 300
CA_PARAMETERS =  cgwErrorRate=0.15
CLOSE_GAPS=1
NUM_THREADS = 30
JF_SIZE = 200000000
SOAP_ASSEMBLY=0
FLYE_ASSEMBLY=0
END**

**Comment by aakashsur** [comment]
I think the error is related to file paths. If `frag_1.fastq` and `frag_2.fastq` are present inside the run folder, perhaps try without the `/root/results` prefix. You should also double check they show up inside the container while you have the shell open.

**Comment by WJT0925** [comment]
Thanks, I realized that my data were "ln -s" from another path, and these links are wrong for docker, so I cp these data in the work path, then it worked.

**Comment by aakashsur** [comment]
Glad to hear it, I believe that if you use `ln` without the softlink flag I should work. That should help save some space.
